### ISSUE TITLE
Removing eyes/installing cybereye without power

### ISSUE THREAD

**Issue by Nentify** [Flaxbeard/Cyberware#10]
I think the effect should be different, if you walk out and your vision goes black, it's almost impossible to put your regular eyes back. While it makes sense that you can't see without any power to cybereyes or no eyes, it's difficult to repair the situation.

**Comment by Flaxbeard** [comment]
What alternative would you suggest?

I will however disable blindness when in Creative mode.

**Comment by Nentify** [comment]
2nd option sounds good for now, but in real life you'd still have touch/hearing. A more complicated solution could be like flickering blocks or vague block outlines or something.

Otherwise, perhaps a 90% opacity black overlay or the nausea effect or something, not quite sure.

**Comment by Nentify** [comment]
That or a way to somehow put your eyes back easier.

**Comment by tterrag1098** [comment]
"Press E to shove eyeball back into face"

This results in 10% vision so you can further repair the situation.

**Comment by UnstableCodeScarlet** [comment]
I'll extend on this- How about the ability to only install one cyber eye, In case you run out of power? Maybe restrict certain modules to requiring 2 eyes instead of just one...

**Comment by Cisien** [comment]
My suggestion is to apply the blindness effect until this situation is resolved. It will let you know something is seriously wrong, give you an opportunity to remedy the situation, and prevent you from playing normally until it is resolved.

**Comment by Utildayael** [comment]
I ran into a terrible scenario of surgery having me more than half dead, blind from the eyes AND having no food to eat to fill bar so I could heal and wander back into the surgery pen to fix myself. :(

++ for 90%. Thankfully a friend was online and came to save a poor stupid blind cyborg.

**Comment by Flaxbeard** [comment]
I think removing 90% of vision may be appropriate - the last 10% can be perhaps explained as a visualization of other sensory input.
