### ISSUE TITLE
[1.11.2][a-0.2.7] Inserting blueprint into engineering table crashes client

### ISSUE THREAD

**Issue by PhillZitt** [Flaxbeard/Cyberware#100]
When I attempt to place a blueprint in the blueprint slot of an Engineering Table, my client crashes.

[Crash Report](https://gist.github.com/PhillZitt/6324a2586ad7f8d9e5d398d042af95a9)

Related, the item name for the blueprints shows as "item.cyberware.blueprint.notBlank.name" and the shift prompt is "cyberware.tooltip.shiftPrompt".

**Comment by HypnoTherapist** [comment]
I have the same problem when placing a blueprint into its slot of the Engineering table. This occured in single player with a 1.11.2 client, Forge v2279. The only mod installed is Cyberware [CRash Report](https://gist.github.com/HypnoTherapist/87beef04106e873cc71ba3e124ff091b)

**Comment by Flaxbeard** [comment]
Make sure you're using Alpha 0.2.8 for 1.11

**Comment by elucent** [comment]
Closing as nothing else was said about this issue and I believe it is fixed. Reopen if this is inaccurate.
