### ISSUE TITLE
[API Request] Add ability to change max essence

### ISSUE THREAD

**Issue by TheUnderTaker11** [Flaxbeard/Cyberware#115]
If that functionality is already there and I missed it then I'm sorry, but what I want to do is be able to raise the max essence on a player. I got a [suggestion here](https://github.com/TheUnderTaker11/GeneticsReborn/issues/30) for my Genetics Reborn mod that would raise the max essence a player can have based on a gene.
As I said if there is already that functionality would you point me to where I can find it since I must have missed it.

**Comment by LatentDesire** [comment]
The suggestion was more for a gene that lowers/removes the red zone (dipping into which requires the use of the anti-rejection drug in the mod.) 

This would be similar to an augment in WIRED: More Augs. It lowers the bar for when you dip into the red zone by 20 (default start of red zone is 20 tolerance remaining).

**Comment by Flaxbeard** [comment]
Good idea. Will implement - potentially as a player attribute.

**Comment by TheUnderTaker11** [comment]
I assumed max essence was what effected the red zone, as in more essence means more things before you hit the red zone
Never played mod just skimmed through api code

**Comment by LatentDesire** [comment]
Still a way to get more maximum essence without changing the configs is a good idea imo, as more and more augments come out down the line. (Not to mention ones added by other mods.)

The use of these two mods together would covers a broad spectrum  of h+ possibilities.

**Comment by Flaxbeard** [comment]
Implemented in 0.2.10. If there's additional functionality you need please ask.
