### ISSUE TITLE
Hardcore Wither Vs Ender Jammer

### ISSUE THREAD

**Issue by Arkeus121** [Flaxbeard/Cyberware#118]
Whilst Playing the invasion modpack by Darkosto I was trying to fight the wither. Due to the "harcore wither" mod it grants the wither the abilty to teleport. This however is not affected by the enderjammer.

**Comment by Flaxbeard** [comment]
The mod creator for Hardcore Wither doesn't trigger the EnderTeleportEvent when the wither teleports - its their call whether or not to do so, but if they don't I can't block it with the jammer.

**Comment by Arkeus121** [comment]
thanks
