### ISSUE TITLE
[Bug]No Item drops form Cyber Zombies

### ISSUE THREAD

**Issue by nikkimas** [Flaxbeard/Cyberware#12]
After a long not succsesfull search for the Robosurgeon, I decided to cheat it in, just to test the mod. Then I went out for the hunt of Cyber Zombies and found them. However, I didnt get 1 drop of about 20 cyber Zombies. So I set the droprate to 100% just for testing reasons. Still no drops.

Minecraft: 1.10.2
Forge: 12.18.1.2014
Cyberware:  0.1.10

Also, it could be a bug that the Robosurgeon doesn't spawn, because I couldnt find in about 7 fresh generated nether Fortresses.

**Comment by Flaxbeard** [comment]
I tested the Robosurgeon spawning in the first build, and the code that affects it wasn't changed since then - but I'll check again. I'll test the zombies, that seems odd and could be a bug.

**Comment by Flaxbeard** [comment]
Just tested with the latest build and was able to get a drop. Were the Cyberzombies naturally spawned? Do you have another mod that might cause this?

**Comment by nikkimas** [comment]
After the natural spawned cyberzombies didnt drop I put the rate tom 100%. After that I was just testing with `/summon cyberware.cyberzombie`. Now I killed a natural spawned cyberzombie and it dropped. Seems to be just the manually summoned zombies. 

Could be another mod, however I have no clue which one it could be.

**Comment by Flaxbeard** [comment]
Unnatrually spawned cyberzombies don't currently spawn with 'ware, though that should probably be changed

**Comment by nikkimas** [comment]
What if I build a powered Spawner with a cyberzombie soul in it? Does that count as naturally?

**Comment by Flaxbeard** [comment]
It should - a vanilla spawner will count as naturally and if the modded spawner works in the same way it should too.

**Comment by nikkimas** [comment]
Can't even get the mods spawned by a Vanilla Spawner to drop it.

**Comment by Flaxbeard** [comment]
Strange. I'll look into it.

**Comment by Flaxbeard** [comment]
Fixed in https://github.com/Flaxbeard/Cyberware/commit/66d90562d5b7228558a1020035f974724aedcbc2
