### ISSUE TITLE
Why isn't the Charger working

### ISSUE THREAD

**Issue by RoboMedZi** [Flaxbeard/Cyberware#135]
![2017-07-04_20 57 37](https://user-images.githubusercontent.com/25993203/27845261-855426a6-60fb-11e7-9fb4-59699a3bcdf8.png)
What am I doing wrong?

**Comment by thespellslinger** [comment]
do you have a power source? if you have the Immersive Engineering mod, you can place the creative capacitor next to that block and charge yourself through the charging station.

**Comment by RoboMedZi** [comment]
I do have Immersive Engineering, I did not know that I could do that, thanks!

**Comment by hay-dude007** [comment]
IT DOESN'T WORK HELP
