### ISSUE TITLE
[suggestion] cryo chamber

### ISSUE THREAD

**Issue by pot-code** [Flaxbeard/Cyberware#146]
How about adding expiration date to human body part? If they are exposed in inventory or somewhere else other than cryo chamber they will get rotten.

PS. The count down get stopped, but not reset.

BTW, as I have shaders installed, I cant see anything in surgery, It was totally dark inside and took me some time to ESCAPE

**Comment by Diamond45123** [comment]
Uhh, I know this is late but it is supposed to be pitch black while you're in surgery.
