### ISSUE TITLE
desync/crashing

### ISSUE THREAD

**Issue by NezcalSpindrake** [Flaxbeard/Cyberware#2]
When placing the robosurgeon on a server, the server crashes most times. If it doesn't crash, the robosurgeon isn't used up on placing, and can't be broken, appearing to break but staying there, revealed upon relogging.

Server crashlog:
http://pastebin.com/FaFXQ0Nf

**Comment by Flaxbeard** [comment]
Confirmed. Working on a fix. Thanks for the report!

**Comment by Flaxbeard** [comment]
Fixed in 0.1.2
