### ISSUE TITLE
Bug: Power storage augments not keeping power across dimensions.

### ISSUE THREAD

**Issue by Rated01010010** [Flaxbeard/Cyberware#20]
Whenever you go to a different dimension, the power always gets reset to 0. 

Also, when you perform surgery, it gets reset to 0. I don't know if that is intended or not. It shouldn't reset to 0 if it hasn't been changed.

**Comment by Flaxbeard** [comment]
Cannot replicate either issue on the newest build of the mod. Can you provide me with more details?

**Comment by Rated01010010** [comment]
The dimension issue seems to only be with the ultra-dense capacitor. And the power resetting after surgery seems to be a Creative mode thing.

**Comment by Flaxbeard** [comment]
Hm. I tried creative and the capacitor and had issues with neither. Does the same thing happen on relog? During dimension switching and surgery the client and server data is resynced.

**Comment by Flaxbeard** [comment]
Fixed in https://github.com/Flaxbeard/Cyberware/commit/648210aa19b7a683292cf137268f923b492253e4 (build 0.1.12)
