### ISSUE TITLE
Spider vision doesn't let you access GUIs

### ISSUE THREAD

**Issue by Melakion** [Flaxbeard/Cyberware#22]
Put a spider eye in for one of my eyes, now I can't open the GUI on the robosurgeon to put my normal eye back in.

No chat, no HUD, no esc menu..

cyberware-1.9.4-1.10.2-beta-0.1.11
Forge 2026

**Comment by Melakion** [comment]
After Alt-F4 and restart I was still in windowed mode instead of fullscreen when I reconnected to server. GUI and spidervision kept flickering back and forth, and I was able to get my normal eye back in. I don't think spidervision is working properly though.

**Comment by 4rz0** [comment]
Works for me, however the click target is not offset to accommodate for the changed view, it's still in the middle of the screen while the click cursor shows below.

**Comment by LatentDesire** [comment]
Didn't know this was a thing. I'll have to check this out. Wonder what would happen if I tried replacing my skin with rotten flesh. Makes me wonder if anyone has thought of genetic engineering as an add-on for this mod.

**Comment by DnTheMn** [comment]
can confirm this is still a think
![2016-10-19_23 14 36](https://cloud.githubusercontent.com/assets/17092159/19540178/8e4c3b70-9655-11e6-8f2f-0317b4dd296b.png)
![2016-10-19_23 21 05](https://cloud.githubusercontent.com/assets/17092159/19540183/97f9b53a-9655-11e6-8c79-d0ce1b65042e.png)

**Comment by DnTheMn** [comment]
im on allthemods v1.37 any more info please let me know :)

**Comment by Flaxbeard** [comment]
Addressed by 39d852b. If the problem persists after the next release, please re-open.

**Comment by Midaychi** [comment]
This issue exists in 1.10.2
No gui or hud, not even an esc menu.
cyberware-1.9.4-1.10.2-beta-0.2.10.jar

![Image of pain and misery](https://dl.dropbox.com/s/rd9hwv1357ptt20/best.png)
