### ISSUE TITLE
TESLA API Crash - modid changed

### ISSUE THREAD

**Issue by mallrat208** [Flaxbeard/Cyberware#28]
Kodos dropped this off in IRC last night - [Crash Log](http://puu.sh/quR1p/ab20634400.txt)
After a quick search, the newest version of TESLA changed it's modid from 'Tesla' to 'tesla' effectively breaking all the @Optional stuff

**Comment by Flaxbeard** [comment]
Hmm... I originally had it lowercase, someone reported it was breaking so I made it uppercase. Why would Telsa change its modid mid-version...

**Comment by mallrat208** [comment]
From what I understand, lowercase MODIDs should be standard going forward or at least in 1.11. Tesla just changed to meet that standard.

https://github.com/Darkhax-Minecraft/Tesla/commit/69f27fc3e225138c06390716e9ed1b19f36c74be

**Comment by Flaxbeard** [comment]
I wonder - can I just double up on the @Optional notations, one for each modid?

**Comment by Flaxbeard** [comment]
Fixed in 0.1.13
