### ISSUE TITLE
Buggy with Sponge

### ISSUE THREAD

**Issue by Nentify** [Flaxbeard/Cyberware#33]
Not sure if the issue lies mainly here or with Sponge, but the mod is a bit buggy when running with Sponge.

More info here: https://github.com/SpongePowered/SpongeForge/issues/844

Perhaps you could offer any insight.

Thanks a lot for your time,
Luke

**Comment by Nentify** [comment]
Here's a video if it helps. Sometimes the legs do get removed properly, but relogging allows you to walk properly again.

http://i.nentify.me/L57mudZn.mp4

I would love to be able to use this mod properly!

**Comment by Flaxbeard** [comment]
At this point in time I don't think I can support Sponge, it's just too different from forge to be able to ensure it works concurrently. A fix is going to need to happen on their end unless this is also happening with base forge.
