### ISSUE TITLE
Double HUD

### ISSUE THREAD

**Issue by seulil** [Flaxbeard/Cyberware#34]
Dunno what cause this but got few mods - which none of changing anything hud related - exluding apple skin, tough as nails or journey map.

Also didn't find any HUD related options in cfg so think will ask here, cuz noone on the internet has the same issue.

heres a pic of my problem
![2016-08-18_23 05 30](https://cloud.githubusercontent.com/assets/8291168/17790769/54018aee-6598-11e6-95f4-dfe7fb2eb364.png)

**Comment by seulil** [comment]
.....can be closed ...testin whit and whitout HUD related mods...and it seems that THOUGH AS NAILS cause this. Double HUD only appears when Thirst bar is on. a bit sad that i can't use both mods cuz like any difficulties, but so let U know...I keep Your mod this time...;p

**Comment by Flaxbeard** [comment]
I've contacted the TAN devs, looks like it's an issue on their end
