### ISSUE TITLE
A small bug in "Cyberware Engineering Table"

### ISSUE THREAD

**Issue by RainEffect** [Flaxbeard/Cyberware#36]
![cyberware engineering table](https://cloud.githubusercontent.com/assets/14258727/17877448/e6c520cc-6915-11e6-90c6-5cca06689b8b.png)
Like this...Collision box in the wrong place...
Maybe you can know what I mean...
My English is not good...

**Comment by Flaxbeard** [comment]
My bad! Will fix for the next build
