### ISSUE TITLE
Cyberware scanner time config doing nothing

### ISSUE THREAD

**Issue by drewbit** [Flaxbeard/Cyberware#40]
Trying to change the time taken from 20 minutes to 10 minutes per scanner operation, so I changed the config to what I believe should be correct.

http://imgur.com/a/FaHs6

Restarting the server and going back into the game, I find it's still going to take 20 minutes for some reason:

http://imgur.com/a/Xg5gT

Cyberware Version: cyberware-1.9.4-1.10.2-beta-0.2.1

**Comment by Flaxbeard** [comment]
Looks like it's just a visual issue - if the client config doesn't match the server config it will display an incorrect time

**Comment by Flaxbeard** [comment]
Fixed in 46c751c.
