### ISSUE TITLE
Cyberarm does not render (1st person)

### ISSUE THREAD

**Issue by drewbit** [Flaxbeard/Cyberware#42]
Implanted a cyberarm, it's no longer showing my hand anymore.

My View: http://imgur.com/a/cLW4Y

Index from the Robosurgeon: http://imgur.com/a/SCClR

Cyberware Version: cyberware-1.9.4-1.10.2-beta-0.2.1

**Comment by drewbit** [comment]
... I noticed that if I jump and look down, I see it rendering very strangely:
http://imgur.com/a/6gPaL

**Comment by drewbit** [comment]
Yep, it's rendering off my body somehow, here's another screenshot:
http://imgur.com/a/eUy8z

**Comment by Flaxbeard** [comment]
With 0.2.2, are you still having this issue?

**Comment by drewbit** [comment]
Sorry for the late response, just got around to updating. The issue is still present.

**Comment by Flaxbeard** [comment]
Are you on 1.10 by chance? My dev environment is in 1.9 so that may be why I'm not getting this issue.

**Comment by Towsty** [comment]
In 1.10.2 using [beta-0.2.2] this is me "holding" my sword and jumping. As soon as I changed to a cyber arm it started doing this. Put human arm back but the issue persists. 

![image](https://cloud.githubusercontent.com/assets/5897643/18805142/c853eb9a-81cb-11e6-8506-a1df792b033a.png)

**Comment by Flaxbeard** [comment]
Any chance you could test with just Cyberware installed?

**Comment by Towsty** [comment]
Sure, one sec.

**Comment by drewbit** [comment]
Issue was in 1.10 for me too, Yeah.

**Comment by Towsty** [comment]
Cyberware beta-0.2.2
Forge 12.18.1.2088

![image](https://cloud.githubusercontent.com/assets/5897643/18805269/24a4199a-81ce-11e6-8cf1-dc0a1a57d21f.png)

Oddly enough, after just installing right arm it is now forcing my left arm as main, and not rendering right at all despite changing my settings in skin settings over and over.

![image](https://cloud.githubusercontent.com/assets/5897643/18805278/72a39cb0-81ce-11e6-8610-6f6c1e3b5fec.png)

Then, after installing the left arm it switched the priority back to my right arm. Neither arms are rendering now and there are no items rendering in hand either in first peimage](https://cloud.githubusercontent.com/assets/5897643/18805282/9a7a5be8-81ce-11e6-821c-d7d2ed723101.png)


![image](https://cloud.githubusercontent.com/assets/5897643/18805283/a68c2a24-81ce-11e6-98a0-02fe7641d009.png)

**Comment by Towsty** [comment]
![image](https://cloud.githubusercontent.com/assets/5897643/18805285/b4db11f8-81ce-11e6-93c7-cb62b04e0c06.png)

**Comment by Flaxbeard** [comment]
Do you have power?

**Comment by Towsty** [comment]
I did not, it works fine when powered.

**Comment by Towsty** [comment]
Its an optifine conflict it seems

**Comment by Flaxbeard** [comment]
Good to know. I think I'll make a temp fix and just have arms render normally (not cybered) in first person with Optifine. Not perfect, but at least it won't be weird like it is now.

**Comment by Towsty** [comment]
Sounds good, thanks for even trying to work with/around optifine. Much appreciated.

**Comment by Towsty** [comment]
Woot! Patch works, thanks a lot!
