### ISSUE TITLE
General server lag on LivingUpdateEvent.

### ISSUE THREAD

**Issue by LemADEC** [Flaxbeard/Cyberware#47]
We're using forge-1.10.2-12.18.1.2079-universal.jar and cyberware-1.9.4-1.10.2-beta-0.2.2.jar.
It appears lots of LivingUpdateEvent handlers from the mod are using 1.5% of CPU with only 2 players online and no special modifications of them.
According to profiler results, handlers are created redundantly for each effect with what appears to be fairly slow filtering.
Also, the muscle upgrade handler actively tries to remove attributes even if they are already removed which cause CPU (and in some cases NETWORK) lag.

**Comment by Flaxbeard** [comment]
Thanks for the report. I'll look into ways to decrease this lag.

**Comment by Flaxbeard** [comment]
Could you tell me if the [newest build](https://minecraft.curseforge.com/projects/cyberware/files/2333106) resolves these issues? Thanks!

**Comment by LemADEC** [comment]
The related modpack was removed as it accumulated too many issues.
I did a quick comparison between 0.2.2 and 0.2.3, the latest is more efficient and seems to address the original issue.

**Comment by Flaxbeard** [comment]
Sounds good. Thanks for the help! 

If you find the issue persists down the line let me know.
