### ISSUE TITLE
Synth Skin Hiding Wings

### ISSUE THREAD

**Issue by Tenebris11** [Flaxbeard/Cyberware#50]
Hello, as the title states, the synthetic skin augment is hiding wings from Extra Utilities and anything from the Tails mod.  This is a shame, since I would like to use the cyberarms and legs, but they don't render correctly which forces me to use the synthetic skin which is also a problem since I really like the look of my character with wings.  I hope this gets fixed soon, since your mod seems very well made, despite being slightly too difficult to obtain augments.

(As a side note, I can't seem to take out the metabolic generator, so I wanted to know if that is a feature or a bug.)

**Comment by Flaxbeard** [comment]
Are you using optifine?

Metabolic gen issue may be a bug. Have you been able to remove other augs? What happens when you try to remove the gen?

**Comment by Tenebris11** [comment]
I couldn't remove the salvaged generator until I spawned a normal one and replaced the salvaged one with the normal one.  Also, I am using Optifine, so that may be the issue, I suppose.

**Comment by Tenebris11** [comment]
Also, yes I have been able to remove all other augs except for the salvaged metabolic gen.

**Comment by Flaxbeard** [comment]
Do the wings show up without synthskin?

**Comment by Tenebris11** [comment]
Yes, they do.

**Comment by Flaxbeard** [comment]
Addressed with a config option in a1dcdf4.
