### ISSUE TITLE
not getting salvage level parts with woot mod(cyberware mod)

### ISSUE THREAD

**Issue by DeathOfTime** [Flaxbeard/Cyberware#55]
http://i.imgur.com/2PIQGmq.png
i was testing if woot obeys sub-types of mobs for later when i found that when it was working on cyber zombies all the drops it got were manufactured quality and not salvage quality. Not for sure what to do about that in my game. Not even sure where to report it. So letting both mod authors have a glance at it on there respective githubs. 

will try and edit in the links to both posts. I don't care for re-posting. I don't really know how else to do it though.

https://github.com/Flaxbeard/Cyberware/issues/55
https://github.com/Ipsis/Woot/issues/113

edit: the salvaged part that is in there was from before i tested. forgot to removed it. I got that off the zombie i set the woot mob prism with.

Edit:
woot-1.10.2-1.2.0.jar
cyberware-1.9.4-1.10.2-beta-0.2.3.jar
in the "Spilled Juice" pack on the AT launcher. pack version 0.2.3.1.C

**Comment by Ipsis** [comment]
Flaxbeard - The issue with interaction between Cyberware and Woot, is completely on Woot's side. Woot is used to generate loot dropped from mobs, without generating entities in the world. I therefore learn from other kills and some background generated fakeplayer kills.

However I was not calling the doSpecialSpawn handler, meaning that your special spawn setup was not being called.  I also don't let the doEntityUpdate call to be made on the mobs I generate to learn from, which meant that the addRandomCyberware call was not called to give the mob random loot.

I am blacklisting Cyberware in Woot to prevent anyone from using it to farm the mobs.

From reading your mod information, it is based around player combat with zombies to acquire the Cyberware gear. I therefore feel that it is extremely unfair to allow users to use Woot to bypass the mechanics of your mod.

**Comment by Flaxbeard** [comment]
@Ipsis It is my intent that players aren't able to farm Cyberzombies. I appreciate you blacklisting the mod, thank you so much for solving this issue!
