### ISSUE TITLE
Server errors with Food-based drive

### ISSUE THREAD

**Issue by LordEpos** [Flaxbeard/Cyberware#66]
Was really enjoying this mod in a modpack with some friends, but I applied a cyber-ware piece that consumed food to apply power. When I got up for a little while, I ran out of food apparently, and now I get kicked off of the multiplayer server whenever I connect.
I have yet to attempt to replicate the issue offline, don't know if it's a thing in singleplayer.

Only 95% sure this is even your fault. Sorry. :3

**Comment by luckdemon** [comment]
Same error, here's the log file.
http://pastebin.com/zn9C2igG

**Comment by mrAppleXZ** [comment]
Same error.

**Comment by ssblur** [comment]
I am running into the same issue, actually. but I am not out of food, but a NoSuchMethodError is raised when the mod tries to call  net.minecraft.util.FoodStats.func_75119_b.

**Comment by HardwareAccelerated** [comment]
I'm having the exact same issue on an mp server http://pastebin.com/w6wSwv1E

**Comment by Flaxbeard** [comment]
For now revering to the previous version should work. I'll try to push a fix tonight.

**Comment by Flaxbeard** [comment]
https://minecraft.curseforge.com/projects/cyberware/files/2358078
