### ISSUE TITLE
Installing Metabolic Generator corrupts player data on server

### ISSUE THREAD

**Issue by Professorvennie** [Flaxbeard/Cyberware#67]
We are running version 1.51b of all the mods mod pack with beta 0.2.5 of cyberware.  When a member installed the Metabolic Generator he got an internal server error and could not rejoin the server until I deleted his players data.

If you need any other information let me know.

**Comment by Flaxbeard** [comment]
https://minecraft.curseforge.com/projects/cyberware/files/2358078
