### ISSUE TITLE
Scanner features

### ISSUE THREAD

**Issue by Seyeght** [Flaxbeard/Cyberware#69]
Should there be a config for the scanner to destroy the Cyberware component on failure/success to make a blueprint? Or is it the intention of the creators to have a long scan time with no risk of losing the part and you will eventually guaranteed get the blueprint? (Question only, no action requested) 

Can we add the percentage chance per item in the scanner to the config as well? so a stack of 64 will only give me a 50% chance instead of 5. (actual feature request)

**Comment by Flaxbeard** [comment]
Yes, you're correct on the first point.

If I'm reading the second part correctly, you'll want to look under "Additive chance for Scanner per extra item" in the config. If that's set to 5%, each additional item in the scanner will add 5% to the success rate. If it's 0%, more items does nothing.

**Comment by Seyeght** [comment]
Thanks, just what I was looking for, sorry I missed it.
