### ISSUE TITLE
Hostile mobs wearing cyberware.

### ISSUE THREAD

**Issue by llloyd4** [Flaxbeard/Cyberware#74]
Been playing the Curse of Gaia map, which has the Cyberware mod installed, noticed a few things. First the hostile mobs, skeletons, zombies, etc are wearing trench coats, mirror shades, etc. Also I noticed (and it might be another mod at fault here) that they are crazy fast and hard to kill compared to normal mobs. Like skeletons that's machine gunning arrows or creepers that vanish, except for some green sparkles, before they explode, etc. I don't see an option, like Mekanism, to disable hostile mobs from wearing Cyberware armor and cyberware. Unless the map author removed those options like he did for Mekanism (and I subsequently added back. >.< ) .

**Comment by mallrat208** [comment]
Cyberware only creates Cyberzombies that can have Cyberware installed on them and even then, it's unlikely that it is what is causing your issues.

Given you're also having issues with Creepers and Skeletons, there's probably another mod in the pack that specifically makes those monsters harder.

**Comment by llloyd4** [comment]
Ok, though, mobs are still wearing mirror shades, trench coats, and other armor pieces from this mod.

**Comment by LatentDesire** [comment]
Have you consulted the author of the mod pack? Perhaps this was done intentionally by them somehow.

**Comment by llloyd4** [comment]
Why do you think I made this issue on the mod's Github issue page? So the mod author can see and/or respond, maybe add an option, like Mekanism, to disable it?

**Comment by mallrat208** [comment]
@llloyd4 Zombies will definitely spawn wearing the equipment, but it's not really that strong. It's leather tier at best.

**Comment by llloyd4** [comment]
Better than Mekanism, if you don't disable it in the configs you get zombies wearing obsidian or glowstone armor. >.<

**Comment by Flaxbeard** [comment]
I'll make sure to add a config for the next version

**Comment by llloyd4** [comment]
Thank you. :D

**Comment by Alan19** [comment]
Rapid fire skeletons are added by Special AI

**Comment by darthvader45** [comment]
Now I'd like to see other mobs with cyberware.  I know WIRED adds cyberskeletons, but I'd like to see them in the main mod, alongside cybercreepers, cyberspiders and cyberendermen.

**Comment by LatentDesire** [comment]
Darthvader45 I know there is the Laser Creeper Robot Dino Riders From Space mod. It adds cyberneticly upgraded Creepers and Spiders. It also adds Robot T-Rexes that the upgraded Creepers sometimes ride. The laser Creeper can shoot lasers, and the upgraded spider has a Jetpack that has it fly at you.

It's currently in 1.10.2 and I don't know if/when it will update to 1.11.2. 

Perhaps the 1.10.2 version of Cyberware can have some some kind of mod interaction. (Laser eye perhaps? Or some kind of Jetpack related augment?)

**Comment by darthvader45** [comment]
Maybe mob-specific augments?  Like skeletons could have such ones as the quick-draw flywheels and distance enhancer, zombies could have the hyperoxygenation boost and retractable claws, spiders could have random cyberlimbs and linear actuators for jumping.  Now that would be something to see.
