### ISSUE TITLE
Internal battery salvage is better?

### ISSUE THREAD

**Issue by shivachirr** [Flaxbeard/Cyberware#78]
so i was looking at btterys and i notice the salvaged internal battery stores 15000 while the non salvage versio dose only 3000 i sense typo of some kind that needs to be fixed

**Comment by shivachirr** [comment]
yes other then the 15k one is the salvaged and the non salvaged is 3k

**Comment by shivachirr** [comment]
well it used to say 15K now it seems to of fixed its self weird

**Comment by VeloxAzo** [comment]
Not a bug, just misleading. A stack of batteries shows the total amount they'll add when installed as a stack.
