### ISSUE TITLE
Issue with replacing eyes, can't move or see inventory or interact with anything now

### ISSUE THREAD

**Issue by DilemmaMDB** [Flaxbeard/Cyberware#79]
I was using Cyberware for the first time. I saw when I hovered over Spider Eyes that it said they could be used to see in low light. So I used the GUI for the Robosurgeon on a correctly assembled surgery machine and replaced my eyes with spider eyes. When I came out, I was seeing 5 of everything, I guess somewhat similar to what a spider might see? I couldn't interact with my GUI any longer, I can't access my inventory, I can't access my menu...I can't access anything. I tried going back into the chamber and seeing if that might fix it, but it killed me. When I respawned I was still in the chamber, but now I can't move. This is on a multiplayer survival server. Is there anything you can recommend so I can fix this? Or did I just basically destroy my char?

**Comment by DilemmaMDB** [comment]
Closing my own issue here. I re-entered the world and I had died and I saw "Respawn" for a split second on the screen before I was frozen again. I clicked around, randomly, and must have managed to hit that and when i respawned, my eyes were back. All's good.

**Comment by LatentDesire** [comment]
Did this happen on the latest version? Does the same thing happen again if you do the same? If yes, then you may have closed this issue prematurely. I think I remember seeing something else buggy with the spider eyes that had been fixed in current versions.
