### ISSUE TITLE
Neural Contextualizer doesn't work with attacking mobs.

### ISSUE THREAD

**Issue by DRTR0** [Flaxbeard/Cyberware#8]
I am frustrated with a few things in the Neural Contextualizer.

1) When you attack a mob and miss, it switches to your shovel, assuming because you hit the ground or were aiming at the ground.

2) When you actually hit a mob and any tool is in your hand, it doesn't switch to your sword, or whichever tool in your hotbar has the highest attack damage. 

Meaning, 99% of the time I get in a fight with any mob, it switches to a shovel and doesn't switch to anything else. It's so annoying with spiders and baby zombies.

MC Version: 1.10.2
Forge Version: 12.18.1.2011
Cyberware Version: beta-0.1.81

**Comment by Flaxbeard** [comment]
The second part is not a bug - that's intended in case you have a weapon that doesn't do as high damage but has other effects. The first part is understandably annoying - perhaps I'll try to disable it while in combat.

**Comment by DRTR0** [comment]
@Flaxbeard I was just testing with a diamond shovel, axe and sword in my hotbar. I'm pretty certain an axe or sword is better than a shovel.

**Comment by DRTR0** [comment]
https://github.com/thebombzen/AutoSwitch/ correctly handles attacking.

**Comment by Flaxbeard** [comment]
The Neural Contextualizer also specifies that it only works on tools - check out Wired Reflexes T2+ for autoselect on weapons

**Comment by DRTR0** [comment]
@Flaxbeard 

I wouldn't mind that, as long as it doesn't auto-switch to shovel when mobs attack me :/

**Comment by Flaxbeard** [comment]
The Neural Contextualizer now won't switch from tools that extend ItemSword or have "sword" in the unlocalized name. Is this a sufficient solution for the issue?

**Comment by Flaxbeard** [comment]
This change is now available in Build 0.1.10
