### ISSUE TITLE
Ticking entity exception when the creeper explodes.

### ISSUE THREAD

**Issue by Tyrant0x1** [Flaxbeard/Cyberware#81]
With the 0.2.6 beta version of the mod, I'm experiencing a ticking entity exception whenever a creeper explodes. Here is the crash log file: 
[crash-2017-01-17_18.15.21-server.txt.zip](https://github.com/Flaxbeard/Cyberware/files/712868/crash-2017-01-17_18.15.21-server.txt.zip)

**Comment by tali713** [comment]
One line fix to ItemCyberlimb.java, sorry for no patch provided...
replace 
`if (event.getSound() == SoundEvents.ENTITY_PLAYER_HURT && e.worldObj.isRemote)
with
`if (e instanceof EntityPlayer && event.getSound() == SoundEvents.ENTITY_PLAYER_HURT && e.worldObj.isRemote)
