### ISSUE TITLE
Suggestion - Power usage readout

### ISSUE THREAD

**Issue by shivachirr** [Flaxbeard/Cyberware#82]
im thinking on the hud jack/lense i think next to the power meter is power usage to generation like for the solar skin it would say 4/4 when no power is being used and would say 3/4 when your running the cyber eyes. because right now you really have to do the math to know your current power usage. also in the robosurgen is shows power level changes such as power storage levels and changes to power usages to generation

**Comment by Waisse** [comment]
I suggest to also add tooltip on augments that says if it can be disabled or if it's constant power usage.

**Comment by Flaxbeard** [comment]
Also a good idea
