### ISSUE TITLE
QoL suggestion - auto manage blueprints and recipes 

### ISSUE THREAD

**Issue by VeloxAzo** [Flaxbeard/Cyberware#87]
1) Either:
 Make blueprints stackable,
 or 
Make blueprints not create when disassembling savaged parts when you already have that same blueprint in a linked archive. 

2) Make clicking a blueprint from the archive window via engineering table automatically put the blueprint in the blueprint slot, and attempt to pull the needed components from linked component boxes. 

3) Change the blueprint icon to display what part it is for. Ex) Icon is of the respective part, with a paper blueprint in the corner.

**Comment by Flaxbeard** [comment]
All good ideas. More specifically:

1. If you don't put paper in the engineering table, you won't get blueprints. You can also craft blueprints back into paper if you accidentally make them. I'm on the fence about stacking - it might convey the message that they're consumed or single-use items if they're stackable.

2. This is a good idea - the process of crafting needs to be made more simple.

3. Maybe if shift is held, the display icon changes to the item that would be crafted?

**Comment by YaibaToKen** [comment]
Though, if we assume that blueprints are basically just paper with diagrams printed on it then we can easily see them as stackable.
