### ISSUE TITLE
Crash with new Tough As Nails Version

### ISSUE THREAD

**Issue by GWSheridan** [Flaxbeard/Cyberware#89]
Crashes with new version of Tough as nails version-1.9.4-1.1.1
http://pastebin.com/eLUJYk5L

Cyberware version-1.9.4-1.10.2-beta-0.2.6

**Comment by shivachirr** [comment]
i got this aswell when i went to see if tough as nails would be good for my pack

**Comment by EPIICTHUNDERCAT** [comment]
Indeed TAN updated their API which you need to update!

**Comment by Keetarin** [comment]
Same problem, would you please update the integration thing, that would be awesome.

**Comment by scottosx** [comment]
Just adding my voice to prioritize this request. Cyberware would be a great addition to the Forever Stranded pack. It is getting a lot of exposure at the moment. GWSheridan is the OP of this issue so apparently he was considering this inclusion.

**Comment by jamzam90** [comment]
Im also encountering this issue.

**Comment by Morpheus1101** [comment]
https://puu.sh/vchH4/ded4466d44.txt issue still occuring...would seem a downgrade is in order for TAN an Cyberware to work together

**Comment by elucent** [comment]
I fixed this in the 1.11.2 version, just FYI.

**Comment by EPIICTHUNDERCAT** [comment]
So this is not being fixed in 1.10?

**Comment by Flaxbeard** [comment]
Should have been fixed in the newest 1.10 update that came out about a week and a half ago

**Comment by Morpheus1101** [comment]
I can load a server and client instance with TAN & cyberware present
