### ISSUE TITLE
Crash when putting a blueprint in the engineering table

### ISSUE THREAD

**Issue by bertbashful** [Flaxbeard/Cyberware#94]
Hello,

Like the title says, I get a crash whenever I try to place a blueprint in the engineering table. It works fine for deconstructing parts and generating blueprints, but when I try to use said blueprint, it crashes.
[crash-2017-04-07_11.16.14-client.txt](https://github.com/Flaxbeard/Cyberware/files/906474/crash-2017-04-07_11.16.14-client.txt)

I'm totally in love with this mod! Thanks and let me know if there are any questions I can answer.

**Comment by elucent** [comment]
I think I've fixed this, will release a fixed build shortly.

**Comment by bertbashful** [comment]
This absolutely fixed it! Thanks a million!
