### ISSUE TITLE
[1.11.2] Cyber  Zombies don't have a localized name

### ISSUE THREAD

**Issue by Mohron** [Flaxbeard/Cyberware#96]
![image](https://cloud.githubusercontent.com/assets/3623122/24842430/3ac5694c-1d5d-11e7-8df3-4e9bec55dfeb.png)
![image](https://cloud.githubusercontent.com/assets/3623122/24842441/486bc618-1d5d-11e7-9060-d31384792dc6.png)

**Comment by elucent** [comment]
Fixed, will be in the next release shortly.
